### ISSUE TITLE
System.TypeInitializationException during runtime when embedding Unmanaged Assemblies

### ISSUE THREAD

**Issue by chrisbbe** [postsharp/PostSharp.Community.Packer#5]
While embedding unmanaged assemblies, the following exception is thrown during startup of the application.

```
Application: XXX.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidProgramException
   at PostSharp.Community.Packer.Templates.ILTemplateWithUnmanagedHandler..cctor()

Exception Info: System.TypeInitializationException
   at PostSharp.Community.Packer.Templates.ILTemplateWithUnmanagedHandler.Attach()
   at <Module>..cctor()

Exception Info: System.TypeInitializationException
```

**Comment by gfraiteur** [comment]
Chris, unfortunately we don't have the resources to provide support on this component at the moment. We're working with a reduced team and will focus on our commercially-supported stack for the upcoming weeks. You may try to use Fody.Costura from which this project has been forked. In the future we may provide support on https://github.com/postsharp/Caravela.Open.DependencyEmbedder, which is a port of Costura on our new technology stack, but it is not commercially stable at the moment.

Thank you for your understanding.
